name: Deploy Vault

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install yc CLI
        run: |
          curl https://storage.yandexcloud.net/yandexcloud-yc/install.sh | bash
          echo "$HOME/yandex-cloud/bin" >> $GITHUB_PATH

      - name: Auth in YC
        run: |
          cat <<EOF > key.json
            ${{ secrets.YC_KEY }}
          EOF

          yc config set service-account-key key.json  

      - name: Get kubeconfig
        run: |
          yc managed-kubernetes cluster get-credentials \
            --id catvdvccu2p02r6q66si \
            --external

      - name: Install Helm
        uses: azure/setup-helm@v4

      - name: Deploy Vault
        run: |
          helm repo add hashicorp https://helm.releases.hashicorp.com
          helm repo update

          helm upgrade --install vault hashicorp/vault \
            --namespace vault \
            --create-namespace \
            -f manifests/vault/values.yaml

      - name: Check Vault pods
        run: |
          kubectl get pods -n vault